version: '2'
services:

  db:
    ports:
      - "5555:5432"

  agent:
    volumes:
      - ./app:/app
      - ./ci:/ci
    ports:
      - "8888:8888"
      - "8090:8090"
      - "8080:8080"
      - "8081:8081"
